import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Shift App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='p-10'>
        <h1 className='text-2xl font-bold'>
          Shift App
        </h1>

        <p>
          Track your shifts.
        </p>
      </main>
    </div>
  )
}

export default Home
